### ISSUE TITLE
Difficulté 

### ISSUE THREAD

**Issue by Moncorvo** [s0nik42/veolia-idf#1]
Bonjour s0nik42,

J'ai installé votre script sur mon serveur Domoticz mais j'ai des petites difficulté sur certain paramètres.

Vous trouverez ci-dessous la copie écran et je vous remercie de votre aide.

Cordialement,
![2019-10-27 09_48_46-Merci d'utiliser Greenshot](https://user-images.githubusercontent.com/57059363/67633525-16fba080-f8b1-11e9-9b3f-e599d5debc12.png)

**Comment by s0nik42** [comment]
Bonjour,

 Merci pour ton retour, ces paramètres sont optionnels, ils prennent des valeurs par défaut (download_folder) ou autodetecter (GeckoDriver/firefox) . Si tout du moins tu souhaites les specifier, tu peux les rajouter dans le fichier config.json.

Tiens moi au courant si ca fonctionne :)

**Comment by Moncorvo** [comment]
Bonsoir,

Je suis désolé mais je n'ai pas compris sur le rajout des fichiers dans le fichier config.json.

Pourriez-vous me montrer un exemple sur copie écran ?

**Comment by s0nik42** [comment]
Oui, voici, pour supprimer les Warnings (qui ne sont pas la cause de l'échec de l'execution), il suffit de rajouter les lignes correspondantes aux paramètres en guillemets dans le fichier config.json.
Par exemple :
$ cat config.json
{
    "veolia_login": "XXXX",
    "veolia_password": "XXXXX",
    "veolia_contract": "XXXX",
    "domoticz_server": "XXXX",
    "domoticz_idx": "XXXX",
    "domoticz_login": "",
    "domoticz_password": "",
    "timeout": "30",
    "geckodriver": "/usr/local/bin/geckodriver",
    "download_folder": "/tmp/",
    "firefox": "/usr/local/bin/firefox",
    "geckodriver": "/usr/bin/geckodriver"
}

Ces paramètres ne sont pas nécessaires dans le fichier; lorsqu'ils sont absents le script essaie de trouver par lui meme des valeurs.

La raison de l'erreur dans le screenshot que tu as envoyé semble plutôt lié à l'URL de Domoticz que tu as renseigné.

**Comment by s0nik42** [comment]
Est ce que cela fonctionne pour toi ? peut-on clore le ticket ?

**Comment by Warp95** [comment]
Bonjour s0nik42,
Je rencontre un problème de json (P.J)
Merci pour ton retour.

[veolia.log](https://github.com/s0nik42/veolia-idf/files/3810777/veolia.log)

**Comment by s0nik42** [comment]
Il me manque un peu de debug sur cette erreur, je vais faire un change pour plus tard; en attendant, tu confirmes que :

L url de ton serveur est : http://127.0.0.1:8080
Et que tu n'as pas d authentification 
Tu n'as pas l encryption https d activé  sur ton serveur?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Warp95** [comment]
Bonsoir,

L url de ton serveur est : http://127.0.0.1:8080 -> oui
Et que tu n'as pas d authentification -> non il n'y en a pas
Tu n'as pas l encryption https d activé sur ton serveur? ->non il n'y en a pas

Pour plus de renseignement j'ai passé la commande suivante :
![image](https://user-images.githubusercontent.com/13014428/68247447-28644b80-001b-11ea-8cca-6e8143383c42.png)

**Comment by s0nik42** [comment]
Ok, je viens de faire une correction
Peux tu refaire un "Git pull" depuis le repertoire de l'appli et relancer le script ?

Tiens moi au courant.

Julien

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Warp95** [comment]
Bonsoir,
Merci, j'ai été un peu plus loin avec la correction, mais j'ai encore une erreur : 

> Start virtual display  [EE] Failed to start X on display ":1009" (xdpyinfo check failed).if you launch the script from a ssh connection ensure X11 forwarding is activated

Mais après avoir retirer le mode --debug cet erreur n'apparait plus dan sle fichier log. Par contre j'ai cette erreur ci : 

> Setup Firefox profile urlopen() got multiple values for keyword argument 'body'

Eric

**Comment by s0nik42** [comment]
Tu as la premiere erreur en mode debug car tu dois j'imagine executer ton script sur une machine distante et tu n'as pas le forward SSH d'activé.
A cette étape le mode debug execute firefox et l'affiche a l'écran. Pour que cela fonctionne il est nécessaire que ta configuration SSH te permette d'afficher les applications graphiques distantes sur l'ordinateur depuis lequel tu es connecté.

Pour la seconde erreur urlopen, je vais regarder ce que je trouve. et je te tiens au courant

**Comment by s0nik42** [comment]
Tu pourrais me renvoyer un log complet et me dire ce que te renvoie la commande :
pip3 show urllib3
et si possible  essaie d'installer une version récente de la librairie.

**Comment by Warp95** [comment]
Voici les infos : 
>
> pi@domoticz:~/scripts/veolia-idf $ pip3 show urllib3
> 
> Name: urllib3
> Version: 1.9.1
> Location: /usr/lib/python3/dist-packages
> Requires:
>

**Comment by s0nik42** [comment]
Peux tu mettre a jour ta version de urllib3 ? celle-ci date de 2014 :/

Celle que j'utilise est la 1.24.1 (11/2018)

**Comment by s0nik42** [comment]
Il faudra peut être aussi mettre a jour Firefox tu es en 52.9. Je ne sais pas si tout va fonctionner a partir de 60.9 c'est mieux.

**Comment by Warp95** [comment]
Voila les mis à jour sont faites, mais encore un petit problème , en P.J.
veolia.log
geckodriver.log

**Comment by s0nik42** [comment]
ca commence a prendre forme :) ; je pense que cela vient du fait que tu as un seul contrat et que j'ai développé mon logiciel sur mon compte qui en a 2.

2 Options : 
 - Tu arrives a faire fonctionner le mode debug graphique. Il te faut un environnement X11 fonctionnel et on fait ca a distance.
- Tu mets un Mot de passe bidon sur ton compte; je fais une mise à jour du script en fonction et tu rechanges ton mdp après (y a peut être des infos perso)

**Comment by Warp95** [comment]
Bonsoir,
Oui, nous ne sommes surement pas loin de finaliser.
UID : xxxxxxxx@yyyyyy.com
PWD : xxxxxxxxxx

Voila , rien de perso sur mon compte Veolia :-)

**Comment by s0nik42** [comment]
Voila ca devrait être bon : 
`git pull`

**Comment by Warp95** [comment]
Super ca marche et avec un historique en plus !
![image](https://user-images.githubusercontent.com/13014428/68463249-8442f600-020e-11ea-8c52-042928efe84c.png)

Normal le fichier : geckodriver.log ?
Un grand merci !! Depuis le temps que je n'avais plus de remonté de conso.

Serais tu intéressé de regarder le projet de k20human : https://github.com/k20human/domoticz-atome , qui ne fonctionne plus ? https://total.direct-energie.com/particuliers/electricite/compteur-linky/atome

**Comment by s0nik42** [comment]
Hello,

 Merci à toi aussi, ca m'a permis de rajouter qq fonctionnalités sur le script. Content que ca marche. Le fichier geckodriver.log est généré par le plugin firefox. Il peut être utile. 
 
Si tu apprécies le projet, tu peux rajouter une étoile en haut à gauche ca serait top pour la visibilité
 
 Pour Total bof bof, je te conseillerais de changer pour un fournisseur green ;) https://www.greenpeace.fr/ecolo-watt-comparatif-ecolo-fournisseurs-delectricite/

Ps : penses a supprimer les log que tu as posté. Il y a ton email et ton identifiant Veolia dedans.

Julien
