### ISSUE TITLE
Plus de mise à jours depuis le 19/05 ==> "Litres" is not clickable

### ISSUE THREAD

**Issue by guittou** [s0nik42/veolia-idf#12]
Bonjour,

Depuis le 19/05 j'ai une erreur qui empêche de la mise à jours des données.
Le Problème intervient au moment de la sélection du filtre "Litres" sur la page d'historique de consommation.

Start virtual display                                                         [OK]
Setup Firefox profile                                                       [OK]
Start Firefox                                                                    [OK]
Connexion au site Veolia Eau Ile de France                    [OK]
Waiting for Email                                                            [OK]
Waiting for Password                                                      [OK]
Type Email                                                                       [OK]
Type Password                                                                [OK]
Waiting for submit button                                              [OK]
Click on submit button                                                   [OK]
Wait for MENU contrats or historique                            [OK]
Click on menu : HISTORIQUE                                          [OK]
Wait for bouton Litres                                                     [OK]
Click on bouton litres                                                     [WW] **Encountered errorMessage: Element <button class="slds-button slds-button_neutral slds-button_stateful slds-not-selected small"> is not clickable at point (351,825) because another element <html> obscures it// -> Retrying once**

en mode debug je n'ai pas vu visuellement ou pouvait être le problème.

Si tu as un peu de temps pour regarder.

Merci pour le travail déjà effectué

**Comment by s0nik42** [comment]
Hello,

Bien vu, pareil chez moi; je vais regarder

**Comment by guittou** [comment]
merci

**Comment by s0nik42** [comment]
Chez moi ca marche en mode debug (il recupere bien les données), mais pas en mode normal.
C'est pareil chez toi ?

**Comment by guittou** [comment]
non chez moi j'ai la meme erreur dans les 2 cas

**Comment by guittou** [comment]
en mode debug j'ai noté aussi une fenêtre propre à Firefox qui bloque aussi mais elle n'apparait pas tout le temp

**Comment by s0nik42** [comment]
C'est bon j'ai, tu vas pouvoir tester dans qq minutes le temps que je fasse le commit

**Comment by guittou** [comment]
rapide

**Comment by s0nik42** [comment]
Tu peux tester : 
git pull
./veolia-idf-domoticz.py --run

**Comment by guittou** [comment]
je teste ca tout de suite

**Comment by guittou** [comment]
c'est bon ca fonctionne.

j'ai essayé de trouver la solution tout seul mais un problème de résolution j'étais très loin...

Merci

**Comment by s0nik42** [comment]
le faite que ca avait marcher en mode debug chez moi m'a mis sur la piste. En faite pendant le mode debug j'avais scrollé plus bas dans la page pour voir ce qu'il faisait. 

Bon weekend :)
