### ISSUE TITLE
Valeurs mensuels au lieux des valeurs journaliers

### ISSUE THREAD

**Issue by mdeweerd** [s0nik42/veolia-idf#19]
Vérifiant à tout hazard l'évolution de ma consommation d'eau je constate aujourd'hui que la mise à jour journalière n'était pas effective.

Non pas car il n'y a pas eu de valeurs obtenus auprès du serveur, mais parce que le CSV obtenu contient les valeurs mensuelles et ce n'est (heureusement) pas accepté comme valeur valide:
```csv
Date de relevé;Index relevé (litres);Consommation du jour (litres);Index Mesuré/Estimé
12/2021;559000;5425;Estimé
01/2022;565000;6000;Estimé
02/2022;570271;5271;Mesuré
03/2022;575649;5378;Mesuré
04/2022;581466;5817;Mesuré
05/2022;586900;5434;Mesuré
```

Ceci suggère que le clique "bouton jours" n'a pas été effectif.
Peut-être qqchse à renforcer.

**Comment by s0nik42** [comment]
cale fait systématiquement ?

**Comment by mdeweerd** [comment]
Non, je l'ai constaté pour la récupération de cette nuit et c'est la seule fois depuis le 19 juin.
J'ai déclenché l'opération de matin et c'est ok.  Donc à partir de demain il y aura deux requêtes par jour.

Sinon, il faut peut-être trouver qqchse sur la page pour confirmer que c'est bien passé en jour.

**Comment by mdeweerd** [comment]
Je clôture car je pense avoir ajouté une protection dans le code pour ceci.
