### ISSUE TITLE
Problème "Setup Firefox profile"

### ISSUE THREAD

**Issue by llo94** [s0nik42/veolia-idf#2]
Bonjour,

j'essaie de faire fonctionner le script sur mon PC sous Ubuntu et, en mode debug, j'obtiens le message suivant:

`Setup Firefox profile                                                      [EE] __init__() got an unexpected keyword argument 'service_log_path'`

Avez-vous une idée sur ce qui peut se passer ?
Par ailleurs firefox fonctionne très bien sur mon installation Ubuntu (il s'agit de firefox 70)

Merci d'avance

--
Laurent

**Comment by s0nik42** [comment]
Bonsoir,

Quelle version de selenium et quelle version du geckodriver utilises tu ?

`pip3 show selenium`

Si ta version de selenium est < a 3.14.1, je pense que la mise à jour va régler le problème.

**Comment by s0nik42** [comment]
pas de réponse,je clos le point

**Comment by llo94** [comment]
> pas de réponse,je clos le point

Désolé pour l'absence de réponse, je n'ai pas eu le temps d'allumer mon pc depuis plus d'une semaine...

Merci pour le renseignement, il y avait bien un problème sur la version de Selenium (j’utilisais la version Ubuntu à l'origine, pas la version pip3, c'est corrigé maintenant).

Par contre, j'ai une question: est-il possible de récupérer simplement la valeur de l'index du compteur ? (au lieu de la consommation journalière)

Merci

**Comment by s0nik42** [comment]
Surement si c est dispo dans le fichier telechargeable sur le site, mais pour le reinjecter dans quel device domoticz ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by llo94** [comment]
en fait le compteur correspond à la colonne 2 du csv téléchargé, je ne sais pas encore trop dans quel type de compteur l'injecter. Connaissez-vous un document qui décrit les différents types de compteurs domoticz ? je n'arrive pas trouver une doc correcte sur le sujet...

Sinon j'ai un autre problème, le script a fonctionné au moins 3 fois mais il ne fonctionne pas à tous les coups. J'ai régulièrement cette erreur : 

> `Click on Button telechargement                                             [EE] Message: The element reference of <button class="slds-button slds-button_icon"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed`

Merci pour votre aide et bravo pour le script

**Comment by s0nik42** [comment]
dans ce cas la donnée est recuperable, je n'ai pas trouvé de doc sur ce sujet non plus; je me suis renseigné sur les forums et j'ai lu le code source.

Pour ce qui est de l'erreur il faudrait mettre le script a jour.
`git pull`

C'est une erreur aléatoire du au fonctionnement du site qui peut être lent a rafraichir. Avec la dernière version lorsque le script rencontre ce genre de problème, il réessaie une fois.
