### ISSUE TITLE
Script waits for historique on veolia site (timeout)

### ISSUE THREAD

**Issue by Philtass** [s0nik42/veolia-idf#24]
Hello, Velolia web site doesn't work properly since 14/12/2023, even when consulting manually. 

Consequently the script stops with an error : 

`2023-12-14 01:02:29,292 : OK : Wait for missing lightning-spinner 
2023-12-14 01:02:30,322 : OK : Wait for MENU contrats or historique 
2023-12-14 01:02:32,447 : OK : Click on menu : HISTORIQUE 
2023-12-14 01:02:34,537 : OK : Wait for historique menu 
2023-12-14 01:02:34,538 : ~~ : Wait before clicking (4.0s) 
2023-12-14 01:02:38,627 : OK : Click on historique menu 
2023-12-14 01:03:19,070 : WW : Wait for button Litres Encountered errorMessage: Failed, page timeout (timeout=30)`

When connecting manually, after clicking on "CONSULTER L'HISTORIQUE", the history page is not completely loaded. 

![image](https://github.com/s0nik42/veolia-idf/assets/52087795/2c94780b-763d-4c02-9f9a-9850ad34148e)

I need to click on another display like "Consommation facturée" then "Historique" again to have a complete display.

![image](https://github.com/s0nik42/veolia-idf/assets/52087795/461adff6-cd40-4329-a670-f4ef390a6ee0)

May be we could wait for veolia to fix the problem, but I think they won't do it. 

What can we do ?
Thanks for your help

**Comment by mdeweerd** [comment]
My fork diverged a bit too much I think to automate the backport, but you can verify my changes here and surely backport them:

https://github.com/mdeweerd/MetersToHA/compare/f6f33ff925694890d4c2895366bb6a3cb52d0ca5...meters-to-ha

There's not only the bug - the name of the downloaded file also changed .

**Comment by Philtass** [comment]
PS: je crois que j'aurais pu écrire en français ....

**Comment by Philtass** [comment]
> There's not only the bug - the name of the downloaded file also changed .

I did not see that when downloading manually. The file is still named "historique_jours_litres.csv".

**Comment by mdeweerd** [comment]
> I did not see that when downloading manually. The file is still named "historique_jours_litres.csv".

Maybe variable, but I got an extra " €" before the .csv .  They had to choose a non-ascii character of course!

**Comment by mdeweerd** [comment]
> PS: je crois que j'aurais pu écrire en français ....

Oui.  Ce n'est pas ma langue maternelle ;-).

**Comment by Philtass** [comment]
> Maybe variable, but I got an extra " €" before the .csv . They had to choose a non-ascii character of course!

Maybe you choose history in Euro ? 
![image](https://github.com/s0nik42/veolia-idf/assets/52087795/4a904adb-d7c0-4cf8-a5fc-489fd15051d1)
that gives a file named "historique_jours_Euros €.csv"

**Comment by mdeweerd** [comment]
After implementing the workaround with regards to Veolia's bug on the initial Historique view, I ran into that problem.
This was inside the automation.  Maybe it kept some history of some kind - after implementing the extra workaround.

Maybe I was too hasty in my conclusion, but the workaround does not hurt, it also copes with leftovers of previous downloads if any.

**Comment by Philtass** [comment]
I understand that your fork version works despite the veolia bug and that I should install "MetersToHA" instead of "veolia-idf" ? Did I understand correctly ?

**Comment by mdeweerd** [comment]
What you use is up to you.  I suggested that someone can get inspiration from the fork to update s0nik42/veolia-idf .
If you can setup MetersToHA for your system, that is fine also.  I do not nknow what Home Automation system you use.

**Comment by Philtass** [comment]
> What you use is up to you. I suggested that someone can get inspiration from the fork to update s0nik42/veolia-idf . If you can setup MetersToHA for your system, that is fine also. I do not nknow what Home Automation system you use.

I use Domoticz.

**Comment by Philtass** [comment]
@s0nik42, hello, ce serait possible de faire ce que suggère mdeweerd pour contourner ce bug de veolia ?

**Comment by mdeweerd** [comment]
@Philtass Domoticz est soutenu sous MetersToHA mais la validation dépend des utilisateurs - je crois qu'il y a 1 personne minimum qui utilise cela pour les données Gazpar.

**Comment by s0nik42** [comment]
Hi, yes I can probably backport the 2 commits related to veolia

**Comment by Philtass** [comment]
Ok, please tell me when it's done. I'm not in a hury, I update the domoticz counter manually.

**Comment by Philtass** [comment]
> @Philtass Domoticz est soutenu sous MetersToHA mais la validation dépend des utilisateurs - je crois qu'il y a 1 personne minimum qui utilise cela pour les données Gazpar.

ok, thanks, but I'll wait for s0nik42 to backport the fix in veolia_idf.

**Comment by Philtass** [comment]
> Hi, yes I can probably backport the 2 commits related to veolia

And if you need somebody to test... tell me !

**Comment by mdeweerd** [comment]
> ok, thanks, but I'll wait for s0nik42 to backport the fix in veolia_idf.

There probably was 0 user for Domoticz because it did not work...
Out of curiosity I installed Domoticz, and I fixed MetersToHA.

**Comment by s0nik42** [comment]
Hello, la version actuelle marche bien chez moi, serions nous sur des versions differentes ? 


https://github.com/s0nik42/veolia-idf/assets/30711794/a5ca47d5-2ea3-484f-90df-0aa2fa312de7

**Comment by mdeweerd** [comment]
Le problème se produit quand on clique sur Historique dans le menu de gauche.  L'onglet Historique de droite est vide ensuite.
Quand je suis déjà sur un onglet historique fonctionnel, il suffit de revenir sur contrat dans le menu de gauche et à nouveau sur Historique dans ce même menu.

Pour moi c'est toujours d'actualité à l'heure ou je répond.

**Comment by s0nik42** [comment]
hmmm .... tu utilises quelle version de chrome ?

**Comment by mdeweerd** [comment]
Sur mon PC en interactif c'est : 
Chrome Version 120.0.6099.129 (Build officiel) (64 bits)

Sous docker c'est Starting ChromeDriver 112.0.5615.165   ou  ChromeDriver 119.0.6045.159  (version chromium non remontée).

**Comment by s0nik42** [comment]
@Philtass est ce que tu pourrais essayé avec la version suivante de chromium : 

ii  chromium   106.0.5249.119~linuxmint1+vanessa

**Comment by s0nik42** [comment]
je voudrais voir si ca ne viendrait pas de la version de chromedriver utilisé

**Comment by mdeweerd** [comment]
Voudrais ou voulais?  Ce n'est pas chromedriver car avec le navigateur Chrome sous Windows sans chromedriver, je reproduis le même comportement et un des utilisateurs de MetersToHA aussi.

**Comment by s0nik42** [comment]
Voudrait, chrome / chrome driver sont dans le meme package; si qqu pouvait tester la version de la stack ci-dessus.
Ca tourne toujours bien ici et je n'arrive pas a reproduire le probleme pour le moment.

**Comment by Philtass** [comment]
Hello tous. Même remarque que Mdeweerd. Que j'utilise Chrome en manuel ou le Chromium driver, c'est pareil. Ma version du Chromium driver est 1:85.0.4183.83-0ubuntu2.22.04.1. Je suis pas sous mint, et j'ai déjà la dernière version ubuntu. La version mint que tu proposes d'essayer n'est pas dispo dans les dépôts ubuntu et j'ai pas très envie de mettre le souk dans mes packages. Désolé.

**Comment by Philtass** [comment]
J'ai essayé le chromium d'installer le .deb mais l'install plante.
![image](https://github.com/s0nik42/veolia-idf/assets/52087795/9121327d-d784-46b9-8b5a-8c41c7e590fb)

**Comment by Philtass** [comment]
Le site Véolia est corrigé. Je pense qu'on peut fermer ce topic. Sauf si le pb reste pour d'autres, bien sûr.

**Comment by s0nik42** [comment]
J'ai justement regardé hier et tout fonctionnait pas moi :)
