### ISSUE TITLE
Prb en mode cron

### ISSUE THREAD

**Issue by Warp95** [s0nik42/veolia-idf#4]
Tout vas bien lors je passe le programme en mode command, mais lorsqu'il s'exécute dans le cron j'ai un message d'erreur sur le _"Check if 'geckodriver' is intalled properly"_

00 15 * * * cd /home/pi/scripts/veolia-idf && python3 veolia-idf-domoticz.py -r

veolia.log

**Comment by s0nik42** [comment]
Le chemin de gecko driver est bien : "/home/pi/scripts/veolia-idf/geckodriver" ?
Tu es sur d avoir les droits dessus ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Warp95** [comment]
Je n'est pas le driver gecko dans : /home/pi/scripts/veolia-idf/geckodriver"

Ce qui me perturbe c'est qu'avec le user "pi" en mode command il trouve bien le driver gecko, et avec le cron qui me semble t-il utilise aussi le user "pi" et pour le coup il ne trouve pas le driver.

**Comment by s0nik42** [comment]
2 Solutions, mais privilégier la 1/ :

1/ Ton cron est surement mal configuré, je pense qu'il n'y a pas "/usr/local/bin/" dans ton PATH
rajoute en debut du fichier cron :
 
`PATH=$PATH:/usr/local/bin`

2/ sinon le script accepte que tu forces la valeur du geckodriver, mais ensuite il risque de ne pas trouver firefox , Il faut rajouter dans le config.json la ligne suivante :
"geckodriver" = "/usr/local/bin/geckodriver"

Tiens moi au courant de la solution qui a marché.

**Comment by Warp95** [comment]
Bonsoir, tout est ok !

1/ le fait d'ajouter au début de la crontab la commade PATH fait que les scripts ne s'executent plus, je ne sais pas trop pourquoi se comportement
J'ai donc codé le PATH sur la ligne comme ceci :
_00 15 * * *   PATH=$PATH:/usr/local/bin && python3 /home/pi/scripts/veolia-idf/veolia-idf-domoticz.py -r_ 

2/ c'est option ne semble pas fonctionner le programme génère une erreur.

**Remarque** :
Ce que je ne m'explique pas c'est que /usr/local/bin était bien dans le PATH mais devant la chaine et pour autant cela ne marchait pas !
_pi@domoticz:~ $ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games_

**Comment by s0nik42** [comment]
C'est normal, qd tu fais echo $PATH dans ton shell, tu affiches sa valeur  dans l environnement de ton shell, la plus part du temps cette valeur est réglée dans un des fichiers de configuration du shell

La crontab est un programme different qui n'est pas un processus fils de ton shell, donc il n hérite pas des variables d´environnements de ton shell
Il est donc necessaire de les rajouter dans la co figuration de cron 

Julien

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
