### ISSUE TITLE
shell only

### ISSUE THREAD

**Issue by xAsKeYx** [s0nik42/veolia-idf#5]
Bonjour,

Je ne peux pas faire fonctionne le script car je n'ai pas d’environnement  graphique sur ma debian. Auriez-vous une solution ?

Cordialement,

**Comment by s0nik42** [comment]
>Bonjour, ...

@xAsKeYx bonjour, l environnement graphique n'est nécessaire que pour le debug

A noter que si la debian est accédée depuis un ordinateur distant en SSH il est tout a fait possible d utiliser le mode debug graphique

Une fois que tu as suivis la procedure d install, envois un log du script et je verrais pour t aider a résoudre les PBs restants

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xAsKeYx** [comment]
Log firefox : 
```
srv-askey:/opt/domoticz/plugins/veolia-idf# /opt/domoticz/plugins/veolia-idf/firefox/firefox
Error: no DISPLAY environment variable specified
```
Log du script
```
srv-askey:/opt/domoticz/plugins/veolia-idf# ./veolia-idf-domoticz.py --run --debug
DEBUG MODE ACTIVATED                                                       [WW] only use '--debug' for troubleshooting
Check script version is up to date                                         [OK]
Loading configuration file : /opt/domoticz/plugins/veolia-idf//config.json [OK]
Start loading veolia configuration                                         [--]
    "veolia_login" = "charleynedurand@gmail.com"                           [OK]
    "veolia_password" = "*********"                                        [OK]
    "veolia_contract" = "8354900"                                          [OK]
    "geckodriver" = "/opt/domoticz/plugins/veolia-idf/geckodriver"         [WW] param is not found in config file, using default value
    "firefox" = "/opt/domoticz/plugins/veolia-idf/firefox"                 [WW] param is not found in config file, using default value
    "timeout" = "30"                                                       [OK]
    "download_folder" = "/opt/domoticz/plugins/veolia-idf/"                [WW] param is not found in config file, using default value
    "logs_folder" = "/opt/domoticz/plugins/veolia-idf/"                    [OK]
End loading veolia configuration                                           [OK]
Start Loading Domoticz configuration                                       [--]
    "domoticz_idx" = "189"                                                 [OK]
    "domoticz_server" = "http://192.168.1.30:8080"                         [OK]
    "domoticz_login" = "askey"                                             [OK]
    "domoticz_password" = "****************"                               [OK]
    "timeout" = "30"                                                       [OK]
    "download_folder" = "/opt/domoticz/plugins/veolia-idf/"                [WW] param is not found in config file, using default value
End loading domoticz configuration                                         [OK]
Check download location integrity                                          [OK]
Remove temporary download file                                             [OK]
Check if "geckodriver" is intalled properly                                [OK]
Check if "firefox" is intalled properly                                    [OK]
Check firefox browser version                                              [EE] [Errno 13] Permission denied: '/opt/domoticz/plugins/veolia-idf/firefox'
Close Browser                                                              [OK]
Close Display                                                              [EE] Ended with error : // re-run the program with '--debug' option
```

**Comment by s0nik42** [comment]
>Log firefox :  ...

@xAsKeYx tu  as quoi comme droits sur le binaire de firefox ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xAsKeYx** [comment]
je suis en 755 (+x)

**Comment by s0nik42** [comment]
>je suis en 755 (+x)

@xAsKeYx 
Ca donne quoi si tu executes la command suivante avec le meme user que celui que tu utilises pour executer le script ?

/opt/domoticz/plugins/veolia-idf/firefox --version 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xAsKeYx** [comment]
j'ai ajouté dans le config.json le bon répertoire :
"firefox": "/opt/domoticz/plugins/veolia-idf/firefox/firefox"

On avance :)
`Start virtual display                                                      [EE] Failed to start X on display ":1005" (xdpyinfo check failed).if you launch the script through a ssh connection with '--debug' ensure X11 forwarding is activated
`

**Comment by s0nik42** [comment]
>j'ai ajouté dans le config.json le bon répertoire : ...

@xAsKeYx le mode debug necessite X. as tu essayé sans --debug ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xAsKeYx** [comment]
C'est ok, j'ai rajouté la sortie de log et j'ai vu qu'il restait un problème avec geckodriver
J'ai mis la dernière version et ça fonctionne !

Un grand merci pour ton aide et pour ton script !

**Comment by s0nik42** [comment]
>C'est ok, j'ai rajouté la sortie de log et j'ai vu qu'il restait un problème avec geckodriver ...

@xAsKeYx cool a+ !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
