### ISSUE TITLE
Erreur creation session Firefox

### ISSUE THREAD

**Issue by Scrat95220** [s0nik42/veolia-idf#7]
Bonjour,
J'essai désesperement de faire fonctionner le script sur mon Rasbperry mais je bloque à cette étape : 
Une idée?

Merci

1600468097070	geckodriver	INFO	geckodriver 0.19.1
1600468097080	geckodriver	INFO	Listening on 127.0.0.1:49977
1600468098646	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.iqH5laawSovi"
1600468100393	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1600468100394	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1600468100394	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1600468100395	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1600468100781	Marionette	TRACE	Received observer notification profile-after-change
1600468100896	Marionette	TRACE	Received observer notification command-line-startup
1600468100896	Marionette	TRACE	Received observer notification nsPref:changed
1600468100897	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1600468101533	Marionette	TRACE	Received observer notification toplevel-window-ready
JavaScript error: undefined, line 14: Error: An unexpected error occurred
JavaScript error: moz-extension://a43085fc-27b3-4ecb-9903-249240a6bc10/lib/picture_in_picture_overrides.js, line 15: Error: Incorrect argument types for pictureInPictureParent.setOverrides.
JavaScript error: resource:///modules/sessionstore/SessionStore.jsm, line 1325: uncaught exception: 2147746065
1600468105648	Marionette	TRACE	Received observer notification marionette-startup-requested
1600468105649	Marionette	TRACE	Waiting until startup recorder finished recording startup scripts...
1600468105704	Marionette	TRACE	All scripts recorded.
1600468105705	Marionette	DEBUG	Setting recommended pref app.update.disabledForTesting to true
1600468105706	Marionette	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1600468105708	Marionette	DEBUG	Setting recommended pref browser.tabs.remote.separatePrivilegedContentProcess to false
1600468105708	Marionette	DEBUG	Setting recommended pref browser.tabs.unloadOnLowMemory to false
1600468105709	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1600468105709	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1600468105710	Marionette	DEBUG	Setting recommended pref security.certerrors.mitm.priming.enabled to false
1600468105711	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1600468105857	Marionette	INFO	Listening on port 43069
1600468105858	Marionette	DEBUG	Remote service is active
1600468105899	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:47684
1600468105903	Marionette	DEBUG	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1600468105904	Marionette	DEBUG	0 <- [1,1,{"error":"unknown command","message":"newSession","stacktrace":"WebDriverError@chrome://marionette/content/error.js:175: ... t@chrome://marionette/content/server.js:249:9\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:503:20\n"},null]
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.

**Comment by s0nik42** [comment]
Bonjour,
Désolé, j'ai pas eut bcp de tmeps recemment est ce que ton problème est règlé ?

**Comment by Scrat95220** [comment]
Bonjour, oui c'est réglé. J'ai du recompiler moi-même un geronimo récent pour armv7.
Merci
