### ISSUE TITLE
Modification site veolia

### ISSUE THREAD

**Issue by Shaktohh** [s0nik42/veolia-idf#8]
J'ai du rajouter ça juste avant la ligne :         
self.print('Wait before clicking (10)', end="") 

       ### Cliquer sur le bouton Litres suite a la maj de l'euro par defaut
        self.print('Wait for bouton Litres', end="") #############################################################
        try:
            ep = EC.visibility_of_element_located((By.XPATH,"//span[contains(text(), 'Litres')]/parent::node()"))
            el = self.__wait.until(ep, message="failed, page timeout (timeout=" + self.configuration['timeout'] + ")")
        except Exception:
            raise
        else:
            self.print(st="ok")

        self.print('Click on bouton litres : ' + el.get_attribute('innerHTML') , end="") #############################################################
        try:
            el.click()
        except Exception:
            raise
        else:
            self.print(st="ok")

        ### Cliquer sur le bouton jours suite a la maj du mois par defaut
        self.print('Wait for bouton jours', end="") #############################################################
        try:
            ep = EC.visibility_of_element_located((By.XPATH,"//span[contains(text(), 'Jours')]/parent::node()"))
            el = self.__wait.until(ep, message="failed, page timeout (timeout=" + self.configuration['timeout'] + ")")
        except Exception:
            raise
        else:
            self.print(st="ok")

        self.print('Click on bouton jours : ' + el.get_attribute('innerHTML') , end="") #############################################################
        try:
            el.click()
        except Exception:
            raise
        else:
            self.print(st="ok")

**Comment by s0nik42** [comment]
bonjour Shaktohn, merci pour la correction. Je l'ai rajouté avec qq correctifs rapides
